#' Supported category aliases
#'
#' The allowed values of locale, as used by the business search
#' \code{locale} argument.
#' @references Created via \code{data-raw/get-supported-locales.R}
#' based on the values provided at
#' \url{https://www.yelp.com/developers/documentation/v3/supported_locales}
#' @examples
#' SUPPORTED_LOCALES
#' @export
SUPPORTED_LOCALES <- c("cs_CZ", "da_DK", "de_AT", "de_CH", "de_DE", "en_AU",
  "en_BE", "en_CA", "en_CH", "en_GB", "en_HK", "en_IE", "en_MY", "en_NZ",
  "en_PH", "en_SG", "en_US", "es_AR", "es_CL", "es_ES", "es_MX", "fi_FI",
  "fil_PH", "fr_BE", "fr_CA", "fr_CH", "fr_FR", "it_CH", "it_IT", "ja_JP",
  "ms_MY", "nb_NO", "nl_BE", "nl_NL", "pl_PL", "pt_BR", "pt_PT", "sv_FI",
  "sv_SE", "tr_TR", "zh_HK", "zh_TW"
)

#' Supported category aliases
#'
#' The allowed values of category alias, as used by the business search
#' \code{categories} argument.
#' @references Created via \code{data-raw/get-supported-category-aliases.R}
#' based on the values provided at
#' \url{https://www.yelp.com/developers/documentation/v3/all_category_list}
#' @examples
#' SUPPORTED_CATEGORY_ALIASES
#' @export
SUPPORTED_CATEGORY_ALIASES <- c("3dprinting", "abruzzese", "absinthebars", "acaibowls", "accessories",
  "accountants", "acnetreatment", "active", "acupuncture", "addictionmedicine",
  "adoptionservices", "adult", "adultedu", "adultentertainment",
  "advertising", "aerialfitness", "aerialtours", "afghani", "african",
  "afrobrazilian", "agriturismi", "aircraftdealers", "aircraftrepairs",
  "airductcleaning", "airlines", "airport_shuttles", "airportlounges",
  "airports", "airportterminals", "airsoft", "alentejo", "algarve",
  "allergist", "alsatian", "alternativemedicine", "altoatesine",
  "amateursportsteams", "amusementparks", "andalusian", "anesthesiologists",
  "animalassistedtherapy", "animalholistic", "animalphysicaltherapy",
  "animalshelters", "antiques", "apartments", "appliances", "appraisalservices",
  "apulian", "aquariums", "aquariumservices", "arabian", "arabpizza",
  "arcades", "archery", "architects", "architecturaltours", "argentine",
  "armenian", "arroceria_paella", "artclasses", "artificialturf",
  "artmuseums", "artrestoration", "arts", "artsandcrafts", "artschools",
  "artspacerentals", "artsupplies", "arttours", "asianfusion",
  "assistedliving", "astrologers", "asturian", "ateliers", "attractionfarms",
  "atvrentals", "auctionhouses", "audiologist", "audiovisualequipmentrental",
  "australian", "austrian", "authorized_postal_representative",
  "auto", "auto_detailing", "autocustomization", "autodamageassessment",
  "autoelectric", "autoglass", "autoinsurance", "autoloanproviders",
  "autopartssupplies", "autorepair", "autosecurity", "autoupholstery",
  "auvergnat", "awnings", "ayurveda", "azores", "baby_gear", "backflowservices",
  "backshop", "baden", "badminton", "bagels", "baguettes", "bailbondsmen",
  "bakeries", "balloonservices", "bangladeshi", "bankruptcy", "banks",
  "barbers", "barcrawl", "barreclasses", "bars", "bartenders",
  "bartendingschools", "baseballfields", "basketballcourts", "basque",
  "bathing_area", "batterystores", "battingcages", "bavarian",
  "bbq", "beachbars", "beachequipmentrental", "beaches", "beachvolleyball",
  "beautysvc", "bedbreakfast", "beer_and_wine", "beerbar", "beergarden",
  "beergardens", "beerhall", "beertours", "behavioranalysts", "beira",
  "beisl", "belgian", "bento", "berrichon", "bespoke", "bettingcenters",
  "beverage_stores", "bicyclepaths", "bicycles", "bike_repair_maintenance",
  "bikeassociations", "bikeparking", "bikerentals", "bikerepair",
  "bikes", "bikesharing", "bikeshop", "biketours", "billingservices",
  "bingo", "birdshops", "bistros", "blacksea", "blinds", "blooddonation",
  "blowfish", "blowoutservices", "boatcharters", "boatdealers",
  "boating", "boatrepair", "boattours", "bobsledding", "bocceball",
  "bodycontouring", "bodyshops", "bookbinding", "bookkeepers",
  "bookstores", "bootcamps", "boudoirphotography", "bouncehouserentals",
  "bourguignon", "bowling", "boxing", "brasseries", "brazilian",
  "brazilianempanadas", "brazilianjiujitsu", "breakfast_brunch",
  "breweries", "brewingsupplies", "brewpubs", "bridal", "british",
  "bubblesoccer", "bubbletea", "buddhist_temples", "buffets", "buildingsupplies",
  "bulgarian", "bulkbilling", "bungeejumping", "burgers", "burmese",
  "buses", "businessconsulting", "businessfinancing", "businesslawyers",
  "busrental", "busstations", "bustours", "butcher", "c_and_mh",
  "cabaret", "cabinetry", "cablecars", "cafes", "cafeteria", "cajun",
  "cakeshop", "calabrian", "calligraphy", "cambodian", "campgrounds",
  "candlestores", "candy", "cannabis_clinics", "cannabiscollective",
  "cannabisdispensaries", "cannabisreferrals", "cannabistours",
  "canteen", "cantonese", "car_dealers", "carauctions", "carbrokers",
  "carbuyers", "cardioclasses", "cardiology", "careercounseling",
  "caribbean", "caricatures", "carousels", "carpenters", "carpet_cleaning",
  "carpetdyeing", "carpeting", "carpetinstallation", "carrental",
  "carshares", "carwash", "carwindowtinting", "casinos", "castles",
  "catalan", "catering", "cellphoneaccessories", "centralbrazilian",
  "ceremonialclothing", "challengecourses", "champagne_bars", "cheekufta",
  "cheerleading", "cheese", "cheesesteaks", "cheesetastingclasses",
  "chicken_wings", "chickenshop", "childbirthedu", "childcare",
  "childcloth", "childproofing", "childrensmuseums", "chilean",
  "chimneycakes", "chimneysweeps", "chinese", "chinesebazaar",
  "chinesemartialarts", "chiropractors", "chocolate", "choirs",
  "christmastrees", "churches", "churros", "cideries", "cigarbars",
  "circuittraininggyms", "circusschools", "civiccenter", "climbing",
  "clockrepair", "clothingrental", "clowns", "clubcrawl", "cocktailbars",
  "coffee", "coffeeroasteries", "coffeeshops", "coffeeteasupplies",
  "collegecounseling", "collegeuniv", "colombian", "colonics",
  "comedyclubs", "comfortfood", "comicbooks", "commercialrealestate",
  "commissionedartists", "communitybookbox", "communitycenters",
  "communitygardens", "computers", "concept_shops", "conciergemedicine",
  "condominiums", "congee", "contractlaw", "contractors", "convenience",
  "conveyorsushi", "cookingclasses", "cookingschools", "copyshops",
  "corsican", "cosmeticdentists", "cosmetics", "cosmeticsurgeons",
  "cosmetology_schools", "costumes", "countertopinstall", "countryclubs",
  "countrydancehalls", "couriers", "courthouses", "courtreporters",
  "cprclasses", "craneservices", "cremationservices", "creperies",
  "criminaldefense", "cryotherapy", "csa", "cuban", "cucinacampana",
  "culturalcenter", "cupcakes", "currencyexchange", "currysausage",
  "customcakes", "custommerchandise", "customsbrokers", "cyclingclasses",
  "cypriot", "czech", "czechslovakian", "dagashi", "damagerestoration",
  "dance_schools", "danceclubs", "dancerestaurants", "dancestudio",
  "dancewear", "danish", "datarecovery", "daycamps", "debtrelief",
  "decksrailing", "delicatessen", "delis", "demolitionservices",
  "dentalhygeiniststorefront", "dentalhygienists", "dentalhygienistsmobile",
  "dentists", "departmentsofmotorvehicles", "deptstores", "dermatology",
  "desserts", "diagnosticimaging", "diagnosticservices", "dialysisclinics",
  "dietitians", "digitizingservices", "dimsum", "diners", "dinnertheater",
  "disabilitylaw", "discgolf", "discountstore", "distilleries",
  "divebars", "diveshops", "diving", "divorce", "diyautoshop",
  "diyfood", "djs", "dog_parks", "dogwalkers", "dolmusstation",
  "dominican", "donairs", "donationcenter", "donburi", "donuts",
  "doorsales", "doulas", "dramaschools", "driedfruit", "driveintheater",
  "drivethrubars", "driving_schools", "drugstores", "dryclean",
  "drywall", "duilawyers", "duischools", "dumplings", "dumpsterrental",
  "duplicationservices", "dutyfreeshops", "earnosethroat", "eastern_european",
  "easterngerman", "easternmexican", "eatertainment", "editorialservices",
  "education", "educationservices", "egyptian", "eldercareplanning",
  "electricians", "electronics", "electronicsrepair", "elementaryschools",
  "eltern_cafes", "embassy", "embroideryandcrochet", "emergencymedicine",
  "emergencypethospital", "emergencyrooms", "emilian", "empanadas",
  "employmentagencies", "employmentlawyers", "emstraining", "endocrinologists",
  "endodontists", "engraving", "entertainmentlaw", "enviroabatement",
  "environmentaltesting", "eroticmassage", "escapegames", "estateliquidation",
  "estatephotography", "estateplanning", "ethicgrocery", "ethiopian",
  "evchargingstations", "eventphotography", "eventplanning", "eventservices",
  "excavationservices", "experiences", "eyebrowservices", "eyelashservice",
  "fabricstores", "facepainting", "fado_houses", "falafel", "familydr",
  "farmequipmentrepair", "farmersmarket", "farmingequipment", "farms",
  "farriers", "fashion", "fasil", "fencesgates", "fencing", "fengshui",
  "ferries", "fertility", "festivals", "filipino", "financialadvising",
  "financialservices", "fingerprinting", "firearmtraining", "firedepartments",
  "fireplace", "fireprotection", "firewood", "fireworks", "firstaidclasses",
  "fischbroetchen", "fishing", "fishmonger", "fishnchips", "fitness",
  "fitnessequipment", "flatbread", "fleamarkets", "flemish", "flightinstruction",
  "floatspa", "flooring", "floraldesigners", "florists", "flowers",
  "flyboarding", "fondue", "food", "food_court", "foodbanks", "fooddeliveryservices",
  "foodsafety", "foodstands", "foodtours", "foodtrucks", "football",
  "forestry", "formalwear", "foundationrepair", "framing", "franconian",
  "freediving", "freiduria", "french", "friterie", "friulan", "frozenfood",
  "fueldocks", "funeralservices", "funfair", "furclothing", "furniture",
  "furnitureassembly", "furniturerepair", "fuzhou", "galician",
  "galleries", "gamemeat", "gametruckrental", "garage_door_services",
  "gardeners", "gardening", "gardens", "gastroenterologist", "gastropubs",
  "gaybars", "gelato", "general_litigation", "generaldentistry",
  "generalfestivals", "generatorinstallrepair", "geneticists",
  "georgian", "german", "gerontologist", "gestorias", "giblets",
  "giftshops", "glassandmirrors", "glassblowing", "gliding", "gluhwein",
  "gluten_free", "gokarts", "goldbuyers", "golf", "golfcartdealers",
  "golfcartrentals", "golfequipment", "golflessons", "gourmet",
  "gozleme", "graphicdesign", "greek", "grillingequipment", "grocery",
  "groomer", "groutservices", "guamanian", "guesthouses", "guitarstores",
  "gun_ranges", "guns_and_ammo", "gunsmith", "gutterservices",
  "gymnastics", "gyms", "gyudon", "habilitativeservices", "hainan",
  "hair", "hair_extensions", "hairloss", "hairremoval", "hairstylists",
  "haitian", "hakka", "halal", "halfwayhouses", "halotherapy",
  "handball", "handrolls", "handyman", "hanggliding", "hardware",
  "hats", "hauntedhouses", "hawaiian", "hawkercentre", "hazardouswastedisposal",
  "headshops", "health", "healthcoach", "healthinsurance", "healthmarkets",
  "healthretreats", "healthtrainers", "hearing_aids", "hearingaidproviders",
  "henghwa", "hennaartists", "hepatologists", "herbalshops", "herbsandspices",
  "hessian", "heuriger", "hifi", "highschools", "hiking", "himalayan",
  "hindu_temples", "historicaltours", "hkcafe", "hobbyshops", "hokkien",
  "holidaydecorations", "home_inspectors", "home_organization",
  "homeandgarden", "homeappliancerepair", "homeautomation", "homecleaning",
  "homedecor", "homedevelopers", "homeenergyauditors", "homehealthcare",
  "homeinsurance", "homelessshelters", "homemadefood", "homenetworkinstall",
  "homeopathic", "homeownerassociation", "homeservices", "homestaging",
  "hometheatreinstallation", "homewindowtinting", "honduran", "honey",
  "hookah_bars", "horse_boarding", "horsebackriding", "horsequipment",
  "horseracing", "horumon", "hospice", "hospitalists", "hospitals",
  "hostels", "hot_air_balloons", "hotdog", "hotdogs", "hotel_bar",
  "hotels", "hotelstravel", "hotpot", "hotsprings", "hottubandpool",
  "housesitters", "housingcooperatives", "hunan", "hungarian",
  "huntingfishingsupplies", "hvac", "hybridcarrepair", "hydrojetting",
  "hydroponics", "hydrotherapy", "hypnosis", "iberian", "icecream",
  "icedelivery", "immigrationlawyers", "immunodermatologists",
  "importedfood", "indonesian", "indoor_playcenter", "indoorlandscaping",
  "indpak", "infectiousdisease", "installmentloans", "insulationinstallation",
  "insurance", "interiordesign", "interlocksystems", "internalmed",
  "international", "internetbooth", "internetcafe", "intervaltraininggyms",
  "intlgrocery", "investing", "iplaw", "irish", "irish_pubs", "irrigation",
  "island_pub", "isps", "israeli", "italian", "itservices", "ivhydration",
  "izakaya", "jaliscan", "japacurry", "japanese", "jazzandblues",
  "jetskis", "jewelry", "jewelryrepair", "jewish", "jpsweets",
  "juicebars", "junkremovalandhauling", "junkyards", "kaiseki",
  "karaoke", "karate", "kebab", "kickboxing", "kids_activities",
  "kimonos", "kiosk", "kitchenandbath", "kitchenincubators", "kiteboarding",
  "knifesharpening", "knittingsupplies", "kombucha", "kopitiam",
  "korean", "kosher", "kurdish", "kushikatsu", "laboratorytesting",
  "lactationservices", "lahmacun", "lakes", "lancenters", "landmarks",
  "landscapearchitects", "landscaping", "landsurveying", "language_schools",
  "laos", "laotian", "laser_hair_removal", "laserlasikeyes", "lasertag",
  "latin", "laundromat", "laundryservices", "lawn_bowling", "lawnservices",
  "lawyers", "leather", "lebanese", "legalservices", "libraries",
  "liceservices", "lifecoach", "lifeinsurance", "lighting", "ligurian",
  "limos", "linens", "lingerie", "livestocksupply", "localfishstores",
  "localflavor", "localservices", "locksmiths", "lounges", "luggage",
  "luggagestorage", "lumbard", "lyonnais", "macarons", "machinerental",
  "machineshops", "madeira", "magicians", "mags", "mahjong", "mailboxcenters",
  "makerspaces", "makeupartists", "malaysian", "mamak", "marchingbands",
  "marinas", "marketing", "markets", "marketstalls", "martialarts",
  "masonry_concrete", "massage", "massage_schools", "massage_therapy",
  "massmedia", "matchmakers", "materialeelettrico", "maternity",
  "mattresses", "mauritius", "meatballs", "meats", "medcenters",
  "media", "mediators", "medicalfoot", "medicallaw", "medicalspa",
  "medicalsupplies", "medicaltransportation", "meditationcenters",
  "mediterranean", "menscloth", "menshair", "metalfabricators",
  "metrostations", "mexican", "mideastern", "midwives", "militarysurplus",
  "milkbars", "milkshakebars", "minho", "mini_golf", "mistingsystemservices",
  "mobile_home_repair", "mobiledentrepair", "mobilehomes", "mobileparks",
  "mobilephonerepair", "mobilephones", "mobilityequipment", "modern_australian",
  "modern_european", "mohels", "mongolian", "montessori", "moroccan",
  "mortgagebrokers", "mortgagelenders", "mortuaryservices", "mosques",
  "motodealers", "motorcycle_rental", "motorcycledealers", "motorcyclerepair",
  "motorcyclinggear", "motorepairs", "mountainbiking", "mountainhuts",
  "movers", "movietheaters", "muaythai", "municipality", "museums",
  "musicalinstrumentsandteachers", "musicians", "musicinstrumentservices",
  "musicproduction", "musicvenues", "musicvideo", "mystics", "nailtechnicians",
  "nannys", "napoletana", "nasilemak", "naturopathic", "nephrologists",
  "neurologist", "neuropathologists", "neurotologists", "newamerican",
  "newcanadian", "newmexican", "newzealand", "nicaraguan", "nicois",
  "nightfood", "nightlife", "nikkei", "nonprofit", "noodles", "norcinerie",
  "northeasternbrazilian", "northernbrazilian", "northerngerman",
  "northernmexican", "norwegian", "notaries", "nudist", "nursepractitioner",
  "nursingschools", "nutritionists", "nyonya", "oaxacan", "obgyn",
  "observatories", "occupationaltherapy", "oden", "officecleaning",
  "officeequipment", "officiants", "oilchange", "okinawan", "okonomiyaki",
  "oliveoil", "oncologist", "onigiri", "opensandwiches", "opera",
  "opthamalogists", "opticians", "optometrists", "oralsurgeons",
  "organdonorservices", "organic_stores", "oriental", "orthodontists",
  "orthopedists", "orthotics", "osteopathicphysicians", "osteopaths",
  "othersalons", "otologists", "ottomancuisine", "outdoorfurniture",
  "outdoorgear", "outdoormovies", "outlet_stores", "oxygenbars",
  "oyakodon", "pachinko", "packingservices", "packingsupplies",
  "paddleboarding", "painmanagement", "paintandsip", "paintball",
  "painters", "paintstores", "paintyourownpottery", "pakistani",
  "palatine", "panasian", "panzerotti", "parasailing", "parentingclasses",
  "parking", "parklets", "parks", "parma", "partybikerentals",
  "partybusrentals", "partycharacters", "partyequipmentrentals",
  "partysupplies", "passportvisaservices", "pastashops", "patentlaw",
  "pathologists", "patiocoverings", "pawn", "paydayloans", "payroll",
  "pediatric_dentists", "pediatricians", "pedicabs", "pekinese",
  "pensions", "perfume", "periodontists", "permanentmakeup", "persian",
  "personal_injury", "personal_shopping", "personalassistants",
  "personalcare", "personalchefs", "peruvian", "pest_control",
  "pet_sitting", "pet_training", "petadoption", "petboarding",
  "petbreeders", "petcremation", "pethospice", "petinsurance",
  "petphotography", "pets", "petservices", "petstore", "pettingzoos",
  "pettransport", "pfcomercial", "pharmacy", "phlebologists", "photoboothrentals",
  "photoclasses", "photographers", "photographystores", "physicaltherapy",
  "physicians", "piadina", "pianobars", "pianoservices", "pianostores",
  "pickyourown", "piemonte", "piercing", "pierogis", "pilates",
  "pita", "pizza", "placentaencapsulation", "planetarium", "plasticsurgeons",
  "playgrounds", "playsets", "plumbing", "plus_size_fashion", "podiatrists",
  "poke", "poledancingclasses", "policedepartments", "polish",
  "poolbilliards", "poolcleaners", "poolhalls", "poolservice",
  "popcorn", "popuprestaurants", "popupshops", "portuguese", "postoffices",
  "potatoes", "poutineries", "powdercoating", "prenatal", "preschools",
  "pressurewashers", "pretzels", "preventivemedicine", "printmedia",
  "privateinvestigation", "privatejetcharter", "privateschools",
  "privatetutors", "processservers", "proctologist", "productdesign",
  "professional", "propane", "propertymgmt", "props", "prosthetics",
  "prosthodontists", "provencal", "psychiatrists", "psychic_astrology",
  "psychicmediums", "psychics", "psychoanalysts", "psychologists",
  "psychotechnicaltests", "psychotherapists", "pubfood", "publicadjusters",
  "publicart", "publicmarkets", "publicplazas", "publicrelations",
  "publicservicesgovt", "publictransport", "pubs", "pueblan", "puertorican",
  "pulmonologist", "pulquerias", "pumpkinpatches", "qigong", "races",
  "racetracks", "racingexperience", "radiologists", "radiostations",
  "rafting", "ramen", "ranches", "raw_food", "realestate", "realestateagents",
  "realestatelawyers", "realestatesvcs", "record_labels", "recording_studios",
  "recreation", "recyclingcenter", "refinishing", "reflexology",
  "registrationservices", "registry_office", "rehabilitation_center",
  "reiki", "religiousitems", "religiousorgs", "religiousschools",
  "rentfurniture", "reptileshops", "residences", "resorts", "restaurants",
  "reststops", "retinaspecialists", "retirement_homes", "reunion",
  "reupholstery", "rhematologists", "rhinelandian", "ribatejo",
  "riceshop", "roadsideassist", "robatayaki", "rock_climbing",
  "rodeo", "rodizios", "roman", "romanian", "roofing", "roofinspectors",
  "rotisserie_chicken", "rugs", "russian", "rv_dealers", "rvparks",
  "rvrental", "rvrepair", "ryokan", "safestores", "safetyequipment",
  "sailing", "sakebars", "salad", "salumerie", "salvadoran", "sambaschools",
  "sandblasting", "sandwiches", "sardinian", "saunainstallation",
  "saunas", "scandinavian", "scandinaviandesign", "scavengerhunts",
  "schnitzel", "scooterrentals", "scootertours", "scottish", "screen_printing_tshirt_printing",
  "screenprinting", "scuba", "seafood", "seafoodmarkets", "seasonaldecorservices",
  "security", "securitysystems", "selfdefenseclasses", "selfstorage",
  "senegalese", "seniorcenters", "septicservices", "serbocroatian",
  "service_stations", "servicestations", "sessionphotography",
  "sewingalterations", "sextherapists", "shanghainese", "sharedofficespaces",
  "sharedtaxis", "shavedice", "shavedsnow", "shipping_centers",
  "shoerepair", "shoes", "shoeshine", "shopping", "shoppingcenters",
  "shoppingpassages", "shredding", "shrines", "shutters", "sicilian",
  "signature_cuisine", "signmaking", "silentdisco", "singaporean",
  "skate_parks", "skateshops", "skatingrinks", "skiing", "skillednursing",
  "skincare", "skiresorts", "skischools", "skishops", "skydiving",
  "sledding", "sleepspecialists", "sleepwear", "slovakian", "smog_check_stations",
  "smokehouse", "snorkeling", "snowremoval", "snuggleservices",
  "soba", "social_clubs", "socialsecuritylaw", "softwaredevelopment",
  "solarinstallation", "solarpanelcleaning", "sommelierservices",
  "sophrologists", "soulfood", "soup", "southafrican", "southern",
  "souvenirs", "spanish", "spas", "speakeasies", "specialbikes",
  "specialed", "specialtyschools", "speech_therapists", "speechtraining",
  "spermclinic", "spinesurgeons", "spiritism", "spiritual_shop",
  "sport_equipment_hire", "sportgoods", "sports_clubs", "sportsbars",
  "sportsmed", "sportspsychologists", "sportsteams", "sportswear",
  "spraytanning", "squash", "srilankan", "stadiumsarenas", "stationery",
  "steak", "stereo_installation", "stockings", "streetart", "streetvendors",
  "stripclubs", "stripteasedancers", "structuralengineers", "stucco",
  "studiotaping", "sud_ouest", "sugaring", "sugarshacks", "sukiyaki",
  "summer_camps", "supperclubs", "suppliesrestaurant", "surfing",
  "surflifesaving", "surfschools", "surfshop", "surgeons", "sushi",
  "swabian", "swedish", "swimminglessons", "swimmingpools", "swimwear",
  "swissfood", "synagogues", "syrian", "szechuan", "tabac", "tabernas",
  "tablaoflamenco", "tabletopgames", "tableware", "tacos", "taekwondo",
  "taichi", "taiwanese", "taiyaki", "takoyaki", "talentagencies",
  "tamales", "tanning", "tanningbeds", "taoisttemples", "tapas",
  "tapasmallplates", "tastingclasses", "tattoo", "tattooremoval",
  "tavolacalda", "taxidermy", "taxis", "taxlaw", "taxoffice", "taxservices",
  "tcm", "tea", "teachersupplies", "teambuilding", "teethwhitening",
  "telecommunications", "televisionserviceproviders", "televisionstations",
  "tempura", "tenantlaw", "tennis", "teochew", "teppanyaki", "testprep",
  "tex-mex", "thai", "theater", "themedcafes", "threadingservices",
  "thrift_stores", "tickets", "ticketsales", "tikibars", "tiling",
  "tires", "titleloans", "tobaccoshops", "tofu", "tonkatsu", "torshi",
  "tortillas", "tours", "towing", "towncarservice", "townhall",
  "toxicologists", "toys", "tradamerican", "tradclothing", "tradefairs",
  "traditional_swedish", "trafficschools", "trafficticketinglaw",
  "trailerdealers", "trailerrental", "trailerrepair", "trains",
  "trainstations", "trampoline", "translationservices", "transmissionrepair",
  "transport", "tras_os_montes", "trattorie", "travelagents", "travelservices",
  "treeservices", "trinidadian", "triviahosts", "trophyshops",
  "tropicalmedicine", "truck_rental", "truckdealers", "truckrepair",
  "tubing", "tuina", "turkish", "turkishravioli", "tuscan", "tutoring",
  "tvmounting", "udon", "ukrainian", "unagi", "underseamedicine",
  "uniforms", "university_housing", "unofficialyelpevents", "urgent_care",
  "urologists", "usedbooks", "usedcardealers", "utilities", "uzbek",
  "vacation_rentals", "vacationrentalagents", "valetservices",
  "vapeshops", "vascularmedicine", "vegan", "vegetarian", "vehicleshipping",
  "vehiclewraps", "venetian", "venezuelan", "venison", "venues",
  "vermouthbars", "vet", "veteransorganizations", "videoandgames",
  "videofilmproductions", "videogamestores", "videographers", "vietnamese",
  "vintage", "vinyl_records", "vinylsiding", "virtualrealitycenters",
  "visitorcenters", "vitaminssupplements", "vocalcoach", "vocation",
  "volleyball", "waffles", "waldorfschools", "walkinclinics", "walkingtours",
  "wallpapering", "watch_repair", "watches", "waterdelivery", "waterheaterinstallrepair",
  "waterparks", "waterproofing", "waterpurification", "waterstores",
  "watertaxis", "waxing", "web_design", "wedding_planning", "weddingchappels",
  "weightlosscenters", "welldrilling", "westernjapanese", "whalewatchingtours",
  "wheelrimrepair", "whiskeybars", "wholesale_stores", "wholesalers",
  "wigs", "wildlifecontrol", "wildlifehunting", "willstrustsprobates",
  "windowsinstallation", "windowwashing", "windshieldinstallrepair",
  "wine_bars", "wineries", "winetasteclasses", "winetastingroom",
  "winetours", "wok", "womenscloth", "workerscomplaw", "wraps",
  "xmasmarkets", "yakiniku", "yakitori", "yelpevents", "yoga",
  "youth_club", "yucatan", "yugoslav", "zapiekanka", "zipline",
  "zoos", "zorbing")

#' Supported business attributes
#'
#' The allowed values of business attribute, as used by the business search
#' \code{attribute} argument.
#' @references See the attributes field of the business search documentation.
#' \url{https://www.yelp.com/developers/documentation/v3/business_search}
#' @examples
#' SUPPORTED_BUSINESS_ATTRIBUTES
#' @export
SUPPORTED_BUSINESS_ATTRIBUTES <- c("hot_and_new", "request_a_quote",
  "waitlist_reservation", "deals", "gender_neutral_restrooms")